### ISSUE TITLE
Unepected extrusion

### ISSUE THREAD

**Issue by tnakagome** [nolanyee/blender-path-extrude#4]
Hello!

I have came across this behavior while experimenting with your latest version.

Path and face:
<img width="543" alt="screenshot2" src="https://user-images.githubusercontent.com/19327519/107228894-84a8ed00-6a60-11eb-863b-a3ec825b5933.png">
The path starts at the upper right position in the first quadrant and ends at the origin (0, 0, 0). 

Result:
<img width="543" alt="screenshot" src="https://user-images.githubusercontent.com/19327519/107228797-68a54b80-6a60-11eb-8500-338daf4e4474.png">

What I expect is that the last segment of the pipe goes along the wire, as highlighted in orange, toward the origin.
I am not sure if this is significant but the second vertex is also at the origin.

I am using Blender 2.91.2.

Thanks.

[ExtrusionTest2.zip](https://github.com/nolanyee/blender-path-extrude/files/5944148/ExtrusionTest2.zip)

**Comment by nolanyee** [comment]
Hi,
Currently this add-on treats closed loops by connecting the last vertex with the first. It doesn't have any handling for closed loops that have other parts attached to them. In fact it doesn't have handling for any curve that contains vertices with more than 2 edges connected to it. I believe in your example the vertex at the origin has 3 edges attached to it. This add-on is not equipped to deal with such situations because it relies on the order of vertices in the curve. So it visits vertices 1 to 10, but doesn't revisit vertex 2 at the end. Instead it detects a closed loop and revisits vertex 1. I think it should work if you have a simple path of 11 vertices where the 11th vertex happens to be in the same position as the second one, but is actually a separate vertex.

**Comment by nolanyee** [comment]
While I'm unable to add support for extrusion paths with vertices connected to more than 2 edges, due to the ambiguity in which path to take at these vertices, in version 3.2 I just added the ability to use extrusion paths whose points are out of order. Before it would always extrude in the order the vertices were created (or in a user-defined order if the vertices were resorted). Now, as long as each vertex has no more than 2 edges, there is no ambiguity as to what order the vertices should be in, so the add-on will now extrude from one end of the path to the other end consistently.

**Comment by tnakagome** [comment]
Thanks for your explanation. I understand the limitation. Closing.
