### ISSUE TITLE
Issue #2 returns

### ISSUE THREAD

**Issue by tnakagome** [nolanyee/blender-path-extrude#6]
Hello.

The issue that I reported before seems back again with 2.92.0.
The fix previously made does not seem to help even if I add that particular version to the if statements.

Please use the same file that I have uploaded before and try extrusion.
https://github.com/nolanyee/blender-path-extrude/files/5260310/ExtrusionTest.blend.zip

Thanks.

**Comment by nolanyee** [comment]
The misbehavior looked similar to version 2.90, but is very different in nature. Instead of just changing the sign of the orientation matrix, version 2.92 completely ignores the orientation matrix. It must be a bug in Blender. I managed to create a work around in version 3.4 using multiple rotations along Z, Y, and X axes. It might be a little slower than before since it must perform five times the number of rotations per path vertex.

**Comment by tnakagome** [comment]
Thank you. The source file has several tab chars this time and does not work as expected. Would you fix them please?

**Comment by nolanyee** [comment]
Sorry about that. Bad habit. It should be fixed now.

**Comment by tnakagome** [comment]
Thank you! Good to close.

**Comment by tnakagome** [comment]
Just wanted to let you know that the previous change is valid for 2.93.0.
I've updated my version already.

**Comment by nolanyee** [comment]
That's a relief. Thanks.
